# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cars_pb2 as cars__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cars_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCar = channel.unary_unary(
                '/cars.CarService/CreateCar',
                request_serializer=cars__pb2.Car.SerializeToString,
                response_deserializer=cars__pb2.Car.FromString,
                _registered_method=True)
        self.GetCar = channel.unary_unary(
                '/cars.CarService/GetCar',
                request_serializer=cars__pb2.CarId.SerializeToString,
                response_deserializer=cars__pb2.Car.FromString,
                _registered_method=True)
        self.UpdateCar = channel.unary_unary(
                '/cars.CarService/UpdateCar',
                request_serializer=cars__pb2.Car.SerializeToString,
                response_deserializer=cars__pb2.Car.FromString,
                _registered_method=True)
        self.DeleteCar = channel.unary_unary(
                '/cars.CarService/DeleteCar',
                request_serializer=cars__pb2.CarId.SerializeToString,
                response_deserializer=cars__pb2.CarId.FromString,
                _registered_method=True)
        self.ListCars = channel.unary_unary(
                '/cars.CarService/ListCars',
                request_serializer=cars__pb2.Empty.SerializeToString,
                response_deserializer=cars__pb2.CarList.FromString,
                _registered_method=True)


class CarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCar': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCar,
                    request_deserializer=cars__pb2.Car.FromString,
                    response_serializer=cars__pb2.Car.SerializeToString,
            ),
            'GetCar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCar,
                    request_deserializer=cars__pb2.CarId.FromString,
                    response_serializer=cars__pb2.Car.SerializeToString,
            ),
            'UpdateCar': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCar,
                    request_deserializer=cars__pb2.Car.FromString,
                    response_serializer=cars__pb2.Car.SerializeToString,
            ),
            'DeleteCar': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCar,
                    request_deserializer=cars__pb2.CarId.FromString,
                    response_serializer=cars__pb2.CarId.SerializeToString,
            ),
            'ListCars': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCars,
                    request_deserializer=cars__pb2.Empty.FromString,
                    response_serializer=cars__pb2.CarList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cars.CarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cars.CarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/CreateCar',
            cars__pb2.Car.SerializeToString,
            cars__pb2.Car.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/GetCar',
            cars__pb2.CarId.SerializeToString,
            cars__pb2.Car.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/UpdateCar',
            cars__pb2.Car.SerializeToString,
            cars__pb2.Car.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/DeleteCar',
            cars__pb2.CarId.SerializeToString,
            cars__pb2.CarId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cars.CarService/ListCars',
            cars__pb2.Empty.SerializeToString,
            cars__pb2.CarList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
