# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cars.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncars.proto\x12\x04\x63\x61rs\"\x92\x01\n\x03\x43\x61r\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61te_created\x18\x03 \x01(\t\x12\x15\n\rdate_modified\x18\x04 \x01(\t\x12\x18\n\x10last_modified_by\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x02\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x0c\n\x04year\x18\x08 \x01(\x05\"\x13\n\x05\x43\x61rId\x12\n\n\x02id\x18\x01 \x01(\x03\"\"\n\x07\x43\x61rList\x12\x17\n\x04\x63\x61rs\x18\x01 \x03(\x0b\x32\t.cars.Car\"\x07\n\x05\x45mpty2\xc3\x01\n\nCarService\x12!\n\tCreateCar\x12\t.cars.Car\x1a\t.cars.Car\x12 \n\x06GetCar\x12\x0b.cars.CarId\x1a\t.cars.Car\x12!\n\tUpdateCar\x12\t.cars.Car\x1a\t.cars.Car\x12%\n\tDeleteCar\x12\x0b.cars.CarId\x1a\x0b.cars.CarId\x12&\n\x08ListCars\x12\x0b.cars.Empty\x1a\r.cars.CarListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cars_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAR']._serialized_start=21
  _globals['_CAR']._serialized_end=167
  _globals['_CARID']._serialized_start=169
  _globals['_CARID']._serialized_end=188
  _globals['_CARLIST']._serialized_start=190
  _globals['_CARLIST']._serialized_end=224
  _globals['_EMPTY']._serialized_start=226
  _globals['_EMPTY']._serialized_end=233
  _globals['_CARSERVICE']._serialized_start=236
  _globals['_CARSERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
